### ISSUE TITLE
gmd:dateStamp can either have gco:Date or gco:DateTime

### ISSUE THREAD

**Issue by bo-lu** [Canadian-Geospatial-Platform/hnap-to-geocore-lambda#1]
gmd:dateStamp is a mandatory field in NAP/HNAP but can either gco:Date or gco:DateTime. Currently we are only processing DateTime. 

Code is required to handle both cases.

Test case: 
- [ ] **00e1944e-ae14-4ca8-a0c0-4097b4d9c09e** has gco:Date
- [ ] **005494f2-1848-48d5-abe4-a76a7846f035** has gco:DateTime (works fine)

**Comment by elatsis** [comment]
@bo-lu

**Comment by jvanulde** [comment]
Won't fix. Will be resolved in app.geo.ca v2.
